[package]
name = "azure_iot_rs"
version = "0.1.0"
authors = ["duggaraju@gmail.com"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="0.4.11"
tokio= { version = "0.2.22", features = ["full"] }
serde_json = "1.0.57"
env_logger = "0.7.1"
futures = "0.3.5"
config = "0.10.1"

[build-dependencies]
bindgen="0.54.0"

