[package]
name = "azure_iot_rs"
version = "0.1.0"
authors = ["duggaraju@gmail.com"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="0.4.11"
serde_json = "1.0.57"
config = "0.10.1"

[build-dependencies]
bindgen="0.54.0"

